services:
  webserver:
    image: ghcr.io/flip40/32-degrees:release
    container_name: absolutezero
    restart: always
    ports:
      - "8032:8032"
    environment:
      MYSQL_URL: "cleent:itscoldoutside@tcp(kelvin)/32degrees?parseTime=true"

  db:
    image: beercan1989/arm-mysql:5.7
    container_name: kelvin
    restart: always
    environment:
      MYSQL_USER: cleent
      MYSQL_PASSWORD: itscoldoutside
      MYSQL_ROOT_PASSWORD: itscoldoutside
      MYSQL_DATABASE: 32degrees
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
